package com.nexusmind;

import java.util.Arrays;
import java.util.List;

public class AutomationController {

    private static final int FILE_BATCH_SIZE = 5;
    private static final long SLEEP_DURATION_MS = 60 * 60 * 1000; // 1 hour
    private static final long ERROR_SLEEP_DURATION_MS = 10 * 60 * 1000; // 10 minutes
    private static final List<String> HIGH_PRIORITY_KEYWORDS = Arrays.asList("security", "critical", "crash", "vulnerability");
    private static final List<String> MEDIUM_PRIORITY_KEYWORDS = Arrays.asList("optimize", "performance", "refactor", "improve");

    public static void main(String[] args) {
        System.out.println("Starting NexusMind Automation (Self-Loop Mode Enabled)...");

        CheckpointManager checkpointManager = new CheckpointManager();
        RepoManager repoManager = new RepoManager("https://github.com/glacious83/NexusMind", "C:\\Users\\mmamouze\\IdeaProjects\\NexusMind");
        ImprovementAgent agent = new ImprovementAgent(checkpointManager, repoManager);
        RepoAnalyzer analyzer = new RepoAnalyzer("C:\\Users\\mmamouze\\IdeaProjects\\NexusMind");
        AIPlanner planner = new AIPlanner();
        GitHubIssueManager issueManager = new GitHubIssueManager();

        while (true) {
            System.out.println("\n==== NexusMind New Cycle ====");
            try {
                performAutomationCycle(agent, repoManager, analyzer, planner, issueManager);
                System.out.println("\nCycle completed. Sleeping for 1 hour...");
                Thread.sleep(SLEEP_DURATION_MS);
            } catch (Exception e) {
                handleCycleError(e);
            }
        }
    }

    private static void performAutomationCycle(ImprovementAgent agent, RepoManager repoManager, RepoAnalyzer analyzer,
                                                AIPlanner planner, GitHubIssueManager issueManager) throws Exception {
        repoManager.updateRepo();
        agent.improveNextFiles(FILE_BATCH_SIZE);

        String projectSummary = analyzer.generateProjectSummary();
        String improvementSuggestions = planner.generateImprovementSuggestions(projectSummary);

        Arrays.stream(improvementSuggestions.split("\n"))
              .map(String::trim)
              .filter(suggestion -> !suggestion.isEmpty())
              .forEach(suggestion -> createIssueForSuggestion(issueManager, suggestion));
    }

    private static void createIssueForSuggestion(GitHubIssueManager issueManager, String suggestion) {
        String priority = determinePriority(suggestion);
        String formattedBody = String.format("""
                ### Overview
                This issue was auto-generated by NexusMind AI.

                ### Problem Description
                %s

                ### Suggested Solution
                _(NexusMind recommends improving this area based on project structure analysis.)_

                ### Priority
                %s

                ### Estimated Complexity
                Medium

                ### Additional Notes
                NexusMind can attempt an automated Pull Request once approved.
                """, suggestion, priority);

        issueManager.createIssue(suggestion, formattedBody);
    }

    private static void handleCycleError(Exception e) {
        System.err.println("Error during cycle: " + e.getMessage());
        Notifier.sendError("Error during cycle: " + e.getMessage());
        try {
            Thread.sleep(ERROR_SLEEP_DURATION_MS);
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        }
    }

    private static String determinePriority(String suggestion) {
        String lower = suggestion.toLowerCase();
        if (HIGH_PRIORITY_KEYWORDS.stream().anyMatch(lower::contains)) {
            return "High";
        }
        if (MEDIUM_PRIORITY_KEYWORDS.stream().anyMatch(lower::contains)) {
            return "Medium";
        }
        return "Low";
    }
}
